name: "The Shepherd's Hook"
favicon: null
layout_spectrum: 0.55085
typography_spectrum: 0.80678
title: Advanced Leadership Tools and Techniques based on science and experience
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#034da2'
    - '#85c879'
    - '#5d89ba'
    - '#b6deae'
  brandStrength: 0.19918889575637877
  lightness: 0.9790690052323043
  saturation: 0.5092142310459167
  rhythmicContrast: 0.9037729878909886
purpose: []
